namespace: production
mysql:
  auth:
    username:
      valueFrom:
        secretKeyRef:
          name: kube-secret
          key: DB_USERNAME
    password:
      valueFrom:
        secretKeyRef:
          name: kube-secret
          key: DB_PASSWORD
    database: proddatabase
replicaCount: 2
resources:
  limits:
    cpu: 1
    memory: 1Gi
service:
  type: NodePort
  port: 8080
image:
  tag: latest
