namespace: development
mysql:
  auth:
    secretName: kube-secret
    database: devdatabase
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
service:
  type: ClusterIP
  port: 8080
image:
  tag: dev
