namespace: production
mysql:
  auth:
    username: produser
    password: prodpassword
    database: proddatabase
replicaCount: 5
resources:
  limits:
    cpu: 2
    memory: 2Gi
service:
  type: NodePort
  port: 8080
image:
  tag: latest
