namespace: development
mysql:
  auth:
    username:
      secretKeyRef:
        name: kube-secret
        key: DB_USERNAME
    password:
      secretKeyRef:
        name: kube-secret
        key: DB_PASSWORD
    database: devdatabase
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
service:
  type: ClusterIP
  port: 8080
image:
  tag: dev
