namespace: production
environment: production
mysql:
  auth:
    username: produser
    password: prodpassword
    database: proddatabase
replicaCount: 3
resources:
  limits:
    cpu: "2"
    memory: "2Gi"
