
replicaCount: 3
appName: devops-case-study

image:
  repository: gekoline/devops-case-study
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

mysql:
  auth:
    rootPassword: root_password
    username: myuser
    password: mypassword
    database: mydatabase

  primary:
    service:
      port: 3306

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

volumes:
  - name: app-data
    persistentVolumeClaim:
      claimName: app-data-pvc

volumeMounts:
  - name: app-data
    mountPath: /app/data

