namespace: production
mysql:
  auth:
    username:
      secretKeyRef:
        name: kube-secret
        key: DB_USERNAME
    password:
      secretKeyRef:
        name: kube-secret
        key: DB_PASSWORD
    database: proddatabase
replicaCount: 2
resources:
  limits:
    cpu: 1
    memory: 1Gi
service:
  type: NodePort
  port: 8080
image:
  tag: latest
