namespace: development
mysql:
  auth:
    username: '{{ printf "secretKeyRef:%s:%s" "kube-secret" "DB_USERNAME" }}'
    password: '{{ printf "secretKeyRef:%s:%s" "kube-secret" "DB_PASSWORD" }}'
    database: devdatabase
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
service:
  type: ClusterIP
  port: 8080
image:
  tag: dev
